export const iranianArtists = [
  {
  id: 4,
  name: "ابی",
  genre: "پاپ / راک",
  followers: "۱۵.۲M",
  image: "https://i.pravatar.cc/150?img=21",
  bio: "از ماندگارترین خوانندگان موسیقی پاپ ایران با بیش از پنج دهه فعالیت.",
  albums: [
    {
      title: "شب زده",
      year: 1991,
      cover: "https://picsum.photos/seed/ebi1/80/80"
    }
  ],
  topSongs: [
    {
      title: "خلیج",
      streams: "850M"
    },
    {
      title: "شب زده",
      streams: "720M"
    }
  ]
},
{
  id: 5,
  name: "گوگوش",
  genre: "پاپ",
  followers: "۱۷.۱M",
  image: "https://i.pravatar.cc/150?img=22",
  bio: "خواننده و بازیگر برجسته ایرانی و یکی از نمادهای موسیقی پاپ فارسی.",
},
{
  id: 6,
  name: "معین",
  genre: "پاپ سنتی",
  followers: "۱۳.۸M",
  image: "https://i.pravatar.cc/150?img=23",
  bio: "خواننده محبوب موسیقی عاشقانه با آثار ماندگار در موسیقی ایران.",
},
{
  id: 7,
  name: "اندی",
  genre: "پاپ / دنس",
  followers: "۱۰.۹M",
  image: "https://i.pravatar.cc/150?img=24",
  bio: "از شناخته‌شده‌ترین خوانندگان ایرانی در سطح بین‌المللی.",
},
{
  id: 8,
  name: "شادمهر عقیلی",
  genre: "پاپ",
  followers: "۱۶.۳M",
  image: "https://i.pravatar.cc/150?img=25",
  bio: "خواننده، آهنگساز و نوازنده ایرانی با آثار تأثیرگذار در موسیقی پاپ.",
},
{
  id: 9,
  name: "رضا صادقی",
  genre: "پاپ",
  followers: "۸.۷M",
  image: "https://i.pravatar.cc/150?img=26",
  bio: "خواننده پاپ ایرانی با صدایی خاص و ترانه‌های احساسی.",
},
{
  id: 10,
  name: "احسان خواجه امیری",
  genre: "پاپ",
  followers: "۹.۹M",
  image: "https://i.pravatar.cc/150?img=27",
  bio: "از خوانندگان مطرح موسیقی پاپ ایران با آثار ماندگار.",
},
{
  id: 11,
  name: "بنیامین بهادری",
  genre: "پاپ",
  followers: "۸.۱M",
  image: "https://i.pravatar.cc/150?img=28",
  bio: "خواننده و آهنگساز ایرانی که با آلبوم ۸۵ به شهرت رسید.",
},
{
  id: 12,
  name: "حمید هیراد",
  genre: "پاپ / سنتی",
  followers: "۷.۸M",
  image: "https://i.pravatar.cc/150?img=29",
  bio: "خواننده جوان ایرانی با تلفیق موسیقی سنتی و پاپ.",
},
{
  id: 13,
  name: "گرشا رضایی",
  genre: "پاپ",
  followers: "۶.۴M",
  image: "https://i.pravatar.cc/150?img=30",
  bio: "خواننده و آهنگساز ایرانی با آثار محبوب عاشقانه.",
},
{
  id: 14,
  name: "علیرضا طلیسچی",
  genre: "پاپ",
  followers: "۷.۲M",
  image: "https://i.pravatar.cc/150?img=31",
  bio: "خواننده پاپ ایرانی با آثار پرطرفدار در میان نسل جوان.",
},
{
  id: 15,
  name: "بابک جهانبخش",
  genre: "پاپ",
  followers: "۸.۹M",
  image: "https://i.pravatar.cc/150?img=32",
  bio: "خواننده و آهنگساز ایرانی با سابقه طولانی در موسیقی پاپ.",
},
{
  id: 16,
  name: "فرزاد فرزین",
  genre: "پاپ / الکترونیک",
  followers: "۹.۳M",
  image: "https://i.pravatar.cc/150?img=33",
  bio: "خواننده، آهنگساز و بازیگر ایرانی با سبک مدرن.",
},
{
  id: 17,
  name: "محسن یگانه",
  genre: "پاپ",
  followers: "۱۲.۱M",
  image: "https://i.pravatar.cc/150?img=34",
  bio: "یکی از محبوب‌ترین خوانندگان پاپ ایرانی و خالق آثار پرفروش.",
},
{
  id: 18,
  name: "حامیم",
  genre: "پاپ",
  followers: "۶.۹M",
  image: "https://i.pravatar.cc/150?img=35",
  bio: "از چهره‌های نسل جدید موسیقی پاپ ایران.",
},
{
  id: 19,
  name: "راغب",
  genre: "پاپ",
  followers: "۵.۸M",
  image: "https://i.pravatar.cc/150?img=36",
  bio: "خواننده پاپ ایرانی با آثار عاشقانه و احساسی.",
},
{
  id: 20,
  name: "هوروش بند",
  genre: "پاپ",
  followers: "۷.۴M",
  image: "https://i.pravatar.cc/150?img=37",
  bio: "گروه موسیقی پاپ ایرانی با قطعات پرطرفدار.",
},
{
  id: 21,
  name: "زانیار خسروی",
  genre: "پاپ",
  followers: "۶.۷M",
  image: "https://i.pravatar.cc/150?img=38",
  bio: "خواننده و آهنگساز ایرانی و برادر سیروان خسروی.",
},

];

export const foreignArtists = [
  {
    id: 1,
    name: "The Weeknd",
    genre: "R&B / Pop",
    followers: "110M",
    image: "https://i.pravatar.cc/150?img=33",
    bio: "Canadian singer-songwriter known for his dark, cinematic R&B style and record-breaking hits.",
    albums: [
      { title: "After Hours", year: 2020, cover: "https://picsum.photos/seed/d1/80/80" },
      { title: "Dawn FM", year: 2022, cover: "https://picsum.photos/seed/d2/80/80" },
      { title: "Starboy", year: 2016, cover: "https://picsum.photos/seed/d3/80/80" },
    ],
    topSongs: [
      { title: "Blinding Lights", streams: "4.2B" },
      { title: "Starboy", streams: "2.8B" },
      { title: "Save Your Tears", streams: "2.1B" },
      { title: "Can't Feel My Face", streams: "1.9B" },
      { title: "Die For You", streams: "1.7B" },
    ],
  },
  {
    id: 2,
    name: "Billie Eilish",
    genre: "Alt-Pop / Indie",
    followers: "105M",
    image: "https://i.pravatar.cc/150?img=47",
    bio: "Grammy-winning artist known for her whispery vocals and genre-defying dark pop aesthetic.",
    albums: [
      { title: "When We All Fall Asleep", year: 2019, cover: "https://picsum.photos/seed/e1/80/80" },
      { title: "Happier Than Ever", year: 2021, cover: "https://picsum.photos/seed/e2/80/80" },
      { title: "Hit Me Hard and Soft", year: 2024, cover: "https://picsum.photos/seed/e3/80/80" },
    ],
    topSongs: [
      { title: "bad guy", streams: "3.1B" },
      { title: "Happier Than Ever", streams: "1.8B" },
      { title: "lovely", streams: "2.3B" },
      { title: "Ocean Eyes", streams: "1.4B" },
      { title: "Therefore I Am", streams: "1.2B" },
    ],
  },
  {
    id: 3,
    name: "Drake",
    genre: "Hip-Hop / Rap",
    followers: "95M",
    image: "https://i.pravatar.cc/150?img=60",
    bio: "Toronto-born rapper and global icon dominating charts for over a decade with introspective rap.",
    albums: [
      { title: "Certified Lover Boy", year: 2021, cover: "https://picsum.photos/seed/f1/80/80" },
      { title: "Scorpion", year: 2018, cover: "https://picsum.photos/seed/f2/80/80" },
      { title: "Nothing Was the Same", year: 2013, cover: "https://picsum.photos/seed/f3/80/80" },
    ],
    topSongs: [
      { title: "One Dance", streams: "2.9B" },
      { title: "God's Plan", streams: "2.5B" },
      { title: "Hotline Bling", streams: "2.2B" },
      { title: "In My Feelings", streams: "1.8B" },
      { title: "Started From the Bottom", streams: "1.3B" },
    ],
  },
  {
    id: 4,
    name: "The Weeknd",
    genre: "R&B / Pop",
    followers: "110M",
    image: "https://i.pravatar.cc/150?img=33",
    bio: "Canadian singer-songwriter known for his dark, cinematic R&B style and record-breaking hits.",
    albums: [
      { title: "After Hours", year: 2020, cover: "https://picsum.photos/seed/d1/80/80" },
      { title: "Dawn FM", year: 2022, cover: "https://picsum.photos/seed/d2/80/80" },
      { title: "Starboy", year: 2016, cover: "https://picsum.photos/seed/d3/80/80" },
    ],
    topSongs: [
      { title: "Blinding Lights", streams: "4.2B" },
      { title: "Starboy", streams: "2.8B" },
      { title: "Save Your Tears", streams: "2.1B" },
      { title: "Can't Feel My Face", streams: "1.9B" },
      { title: "Die For You", streams: "1.7B" },
    ],
  },
  {
    id: 5,
    name: "Billie Eilish",
    genre: "Alt-Pop / Indie",
    followers: "105M",
    image: "https://i.pravatar.cc/150?img=47",
    bio: "Grammy-winning artist known for her whispery vocals and genre-defying dark pop aesthetic.",
    albums: [
      { title: "When We All Fall Asleep", year: 2019, cover: "https://picsum.photos/seed/e1/80/80" },
      { title: "Happier Than Ever", year: 2021, cover: "https://picsum.photos/seed/e2/80/80" },
      { title: "Hit Me Hard and Soft", year: 2024, cover: "https://picsum.photos/seed/e3/80/80" },
    ],
    topSongs: [
      { title: "bad guy", streams: "3.1B" },
      { title: "Happier Than Ever", streams: "1.8B" },
      { title: "lovely", streams: "2.3B" },
      { title: "Ocean Eyes", streams: "1.4B" },
      { title: "Therefore I Am", streams: "1.2B" },
    ],
  },
  {
    id: 6,
    name: "Drake",
    genre: "Hip-Hop / Rap",
    followers: "95M",
    image: "https://i.pravatar.cc/150?img=60",
    bio: "Toronto-born rapper and global icon dominating charts for over a decade with introspective rap.",
    albums: [
      { title: "Certified Lover Boy", year: 2021, cover: "https://picsum.photos/seed/f1/80/80" },
      { title: "Scorpion", year: 2018, cover: "https://picsum.photos/seed/f2/80/80" },
      { title: "Nothing Was the Same", year: 2013, cover: "https://picsum.photos/seed/f3/80/80" },
    ],
    topSongs: [
      { title: "One Dance", streams: "2.9B" },
      { title: "God's Plan", streams: "2.5B" },
      { title: "Hotline Bling", streams: "2.2B" },
      { title: "In My Feelings", streams: "1.8B" },
      { title: "Started From the Bottom", streams: "1.3B" },
    ],
  },
];

export const suggestedAlbums = [
  { title: "After Hours", artist: "The Weeknd", year: 2020, cover: "https://picsum.photos/seed/d1/120/120", genre: "R&B" },
  { title: "صبح بی‌خورشید", artist: "محسن چاوشی", year: 1398, cover: "https://picsum.photos/seed/a1/120/120", genre: "پاپ" },
  { title: "Happier Than Ever", artist: "Billie Eilish", year: 2021, cover: "https://picsum.photos/seed/e2/120/120", genre: "Alt-Pop" },
  { title: "دلربا", artist: "سیروان خسروی", year: 1399, cover: "https://picsum.photos/seed/b2/120/120", genre: "پاپ" },
  { title: "Dawn FM", artist: "The Weeknd", year: 2022, cover: "https://picsum.photos/seed/d2/120/120", genre: "Synth-Pop" },
  { title: "خوبی یا نه", artist: "ماکان بند", year: 1397, cover: "https://picsum.photos/seed/c1/120/120", genre: "پاپ" },
  { title: "Dawn FM", artist: "The Weeknd", year: 2022, cover: "https://picsum.photos/seed/d2/120/120", genre: "Synth-Pop" },
  { title: "خوبی یا نه", artist: "ماکان بند", year: 1397, cover: "https://picsum.photos/seed/c1/120/120", genre: "پاپ" },
];
